-- V1__initial_schema.sql

-- Create the 'admin' table
CREATE TABLE admin (
    id VARCHAR(255) PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE
);

-- Create the 'student' table
CREATE TABLE student (
    id VARCHAR(255) PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    registration_year BIGINT NOT NULL
);

-- Define a sequence for book IDs, used by the trigger
CREATE SEQUENCE IF NOT EXISTS books_id_seq;

-- Define a function to generate unique book IDs for the trigger
-- Note: The 'when ((new.id is null))' clause in the trigger below might have
-- an unexpected interaction with 'id int4 NOT NULL'. If 'id' is NOT NULL,
-- 'new.id IS NULL' will only be true if explicitly set to NULL, which would
-- then violate the NOT NULL constraint. If the intent is for the ID to always
-- be generated when not provided, consider making 'id' nullable or removing
-- the 'when' clause from the trigger (and the function would always assign NEW.id).
CREATE OR REPLACE FUNCTION generate_unique_book_id()
RETURNS TRIGGER AS $$
BEGIN
    NEW.id := nextval('books_id_seq');
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create the 'books' table with updated schema
CREATE TABLE public.books (
	id int4 NOT NULL,
	title varchar(255) NOT NULL,
	author varchar(255) NOT NULL,
	field varchar(255) NOT NULL,
	isbn varchar(255) NULL,
	publisher varchar(255) NULL,
	publication_year varchar(255) NULL,
	isavailable bool DEFAULT true NULL,
	CONSTRAINT books_isbn_key UNIQUE (isbn),
	CONSTRAINT books_pkey PRIMARY KEY (id)
);

-- Table Trigger for books to generate ID
CREATE TRIGGER set_book_id
BEFORE INSERT ON public.books
FOR EACH ROW
WHEN ((new.id IS NULL))
EXECUTE FUNCTION generate_unique_book_id();


-- Create the 'book_request' table
-- Note: book_id type changed to INT4 to match the updated books.id type
CREATE TABLE book_request (
    loan_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id INT4 NOT NULL, -- Changed from BIGINT to INT4
    student_id VARCHAR(255) NOT NULL,
    request_date DATE NOT NULL,
    approval_date DATE,
    due_date DATE,
    return_date DATE,
    status VARCHAR(50) NOT NULL, -- Assuming RequestStatus enum values will be stored as strings
    CONSTRAINT fk_book_request_book FOREIGN KEY (book_id) REFERENCES books (id),
    CONSTRAINT fk_book_request_student FOREIGN KEY (student_id) REFERENCES student (id)
);

-- Insert some initial data into the 'books' table
-- Explicitly providing IDs and adding NULL for the new 'publication_year' column
INSERT INTO books (id, title, author, isbn, field, publisher, publication_year, isavailable) VALUES
(1, 'The Great Gatsby', 'F. Scott Fitzgerald', '978-0743273565', 'Fiction', 'Scribner', NULL, TRUE),
(2, '1984', 'George Orwell', '978-0451524935', 'Dystopian', 'Signet Classic', NULL, TRUE),
(3, 'To Kill a Mockingbird', 'Harper Lee', '978-0061120084', 'Fiction', 'Grand Central Publishing', NULL, TRUE),
(4, 'Pride and Prejudice', 'Jane Austen', '978-0141439518', 'Romance', 'Penguin Classics', NULL, TRUE),
(5, 'The Catcher in the Rye', 'J.D. Salinger', '978-0316769174', 'Coming-of-age', 'Little, Brown and Company', NULL, TRUE);
